### ISSUE TITLE
NavBar issues to Fix

### ISSUE THREAD

**Issue by Oegh** [Oegh/digital-menu-landing-page#1]
El NavBar es muy ancho y en la versión móvil ocupa mucho espacio en pantalla. Habría que reducirle el tamaño y tratar de dejarle un tamaño fijo,  aunque la imagen tenga varios tamaños, no importa, fijar la imagen del logo a un tamaño específico.

**TODO:**
- [ ] Fijarle un tamaño al NavBar. 
> Mediante SCSS puede definirle inclusive un tamaño para cuando es un ordenador y otro tamaño para cuando es un dispositivo móvil.

- [ ] A la imagen del logo definirle un tamaño fijo independientemente del tamaño de la imagen. 
>  Igualmente mediante SCSS puedes definirle un tamaño para ordenador y otro para dispositivo móvil.

- [ ] Al desplegar el menú en la versión móvil el fondo del menú tiene transparencia lo que puede causar confusión con las letras e imagen del fondo.
